# Default values for samlet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: absaoss/samlet
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest

# Define any additional environment variables like HTTPS_PROXY etc.
env: []

samlet:
  # ADFS idp endpoint (required)
  #idpEndpoint: "https://example.com"
  idpEndpoint: ""
  # default validity time for issued secrets
  sessionDuration: "1h"

# Default resources for samlet
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi