/*
Copyright 2021 ABSA Group Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/
package config

import (
	"github.com/AbsaOSS/gopkg/env"
	"github.com/pkg/errors"
)

const (
	idpEndpointKey     = "IDP_ENDPOINT"
	awsRegionKey       = "AWS_REGION"
	sessionDurationKey = "SESSION_DURATION"
)

// Config structure
type Config struct {
	IDPEndpoint     string
	AWSRegion       string
	SessionDuration string
}

// GetConfig returns operator config structure
func GetConfig() (*Config, error) {
	idpEndpoint := env.GetEnvAsStringOrFallback(idpEndpointKey, "")
	awsRegion := env.GetEnvAsStringOrFallback(awsRegionKey, "")
	sessionDuration := env.GetEnvAsStringOrFallback(sessionDurationKey, "1h")
	if idpEndpoint == "" {
		return nil, errors.New("IDPEndpoint can't be empty")
	}
	return &Config{
		IDPEndpoint:     idpEndpoint,
		SessionDuration: sessionDuration,
		AWSRegion:       awsRegion,
	}, nil
}
