// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Saml2Aws) DeepCopyInto(out *Saml2Aws) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Saml2Aws.
func (in *Saml2Aws) DeepCopy() *Saml2Aws {
	if in == nil {
		return nil
	}
	out := new(Saml2Aws)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Saml2Aws) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Saml2AwsList) DeepCopyInto(out *Saml2AwsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Saml2Aws, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Saml2AwsList.
func (in *Saml2AwsList) DeepCopy() *Saml2AwsList {
	if in == nil {
		return nil
	}
	out := new(Saml2AwsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Saml2AwsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Saml2AwsSpec) DeepCopyInto(out *Saml2AwsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Saml2AwsSpec.
func (in *Saml2AwsSpec) DeepCopy() *Saml2AwsSpec {
	if in == nil {
		return nil
	}
	out := new(Saml2AwsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Saml2AwsStatus) DeepCopyInto(out *Saml2AwsStatus) {
	*out = *in
	in.ExpirationTime.DeepCopyInto(&out.ExpirationTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Saml2AwsStatus.
func (in *Saml2AwsStatus) DeepCopy() *Saml2AwsStatus {
	if in == nil {
		return nil
	}
	out := new(Saml2AwsStatus)
	in.DeepCopyInto(out)
	return out
}
