apiVersion: v1
entries:
  samlet:
  - apiVersion: v2
    appVersion: v0.1.3
    created: "2021-03-10T10:43:53.0237111Z"
    description: A Helm chart for Kubernetes
    digest: 58813f99989e2f0be3d1c542b66ff118c00d46092156a109831d9a02bc8b2ff8
    name: samlet
    type: application
    urls:
    - https://absaoss.github.io/samlet/charts/samlet-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2021-03-10T10:43:53.022924Z"
    description: A Helm chart for Kubernetes
    digest: 1defccd9408b5fc72cfa4d7867dbde82e2100e8543b207b152271a4bfb43a4e2
    name: samlet
    type: application
    urls:
    - https://absaoss.github.io/samlet/charts/samlet-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: vv0.1.2
    created: "2021-03-10T10:43:53.0240819Z"
    description: A Helm chart for Kubernetes
    digest: 1b71b69bbea818ddba00a2c366059dbe164286dca55217c6bfcfd76dd382efc7
    name: samlet
    type: application
    urls:
    - https://absaoss.github.io/samlet/charts/samlet-v0.1.2.tgz
    version: v0.1.2
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2021-03-10T10:43:53.0214089Z"
    description: A Helm chart for Kubernetes
    digest: 1a59ca37d09e601c1bc5131f5be9a16bd76d3021a398d63b2f1d5f64fdeb3bc1
    name: samlet
    type: application
    urls:
    - https://absaoss.github.io/samlet/charts/samlet-0.1.0.tgz
    version: 0.1.0
generated: "2021-03-10T10:43:53.0198968Z"
