apiVersion: apps/v1
kind: Deployment
metadata:
  name: samlet-controller
  labels:
{{ include "samlet.labels" . | indent 4  }}
spec:
  selector:
    matchLabels:
      controller: samlet
  replicas: 1
  template:
    metadata:
      labels:
        controller: samlet
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        name: samlet
        env:
          - name: IDP_ENDPOINT
            value: {{ .Values.samlet.idpEndpoint }}
          - name: SESSION_DURATION
            value: {{ .Values.samlet.sessionDuration }}
          {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
