# Default values for samlet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: absaoss/samlet 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest 

samlet:
  # ADFS idp endpoint (required)
  #idpEndpoint: "https://example.com"
  idpEndpoint: ""
  # default validity time for issued secrets
  #sessionDurattion: 1h
  sessionDuration: ""
