name: Check

on: pull_request

jobs:
  golang-ci:
    name: Go Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golang-ci
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32
        args: --deadline 2m
