name: Build and relase image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      name: build/push - controller
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: absaoss/samlet
        dockerfile: Dockerfile
        tag_with_ref: true
    - name: compute-tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        echo ::set-output name=semver::${GITHUB_REF#refs/tags/v}
    - uses: k0da/helm-gh-pages-microservices@chart_version
      with:
        access-token: ${{ secrets.REPO_TOKEN }}
        source-charts-folder: 'chart'
        destination-repo: absaoss/samlet
        destination-branch: gh-pages
        helm-package-args: --version=${{ steps.tag.outputs.semver }} --app-version=${{ steps.tag.outputs.tag}}
    - name: Create single node k8s Kind Cluster
      uses: helm/kind-action@v1.0.0-rc.1
      with:
        cluster_name: test-samlet
    - name: Smoke test helm installation
      run: |
         helm repo add samlet https://absaoss.github.io/samlet/
         helm repo update
         helm -n samlet upgrade -i samlet samlet/samlet --wait --create-namespace
