name: Build and relase image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      name: build/push - controller
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: absaoss/samlet
        dockerfile: Dockerfile
        tag_with_ref: true
    - uses: dave-mcconnell/helm-gh-pages-microservices@master
      with:
        access-token: ${{ secrets.REPO_TOKEN }}
        source-charts-folder: 'config/helm'
        destination-repo: absaoss/samlet
        destination-branch: gh-pages
    - name: Create single node k8s Kind Cluster
      uses: helm/kind-action@v1.0.0-rc.1
      with:
        cluster_name: test-samlet
    - name: Smoke test helm installation
      run: |
         helm repo add samlet https://absaoss.github.io/samlet/
         helm repo update
         helm -n samlet upgrade -i samlet samlet/samlet --wait --create-namespace
