name: Build and relase image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v0.159.0
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: compute-tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        echo ::set-output name=semver::${GITHUB_REF#refs/tags/v}
    - uses: stefanprodan/helm-gh-pages@v1.4.1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        charts_dir: chart
        branch: gh-pages
        linting: off
        app_version: ${{ steps.tag.outputs.tag}}
        chart_version: ${{ steps.tag.outputs.semver }}
    - name: Create single node k8s Kind Cluster
      uses: helm/kind-action@v1.0.0-rc.1
      with:
        cluster_name: test-samlet
    - name: Smoke test helm installation
      run: |
         helm repo add samlet https://absaoss.github.io/samlet/
         helm repo update
         helm -n samlet upgrade -i samlet samlet/samlet --wait --create-namespace
